### ISSUE TITLE
foo. j file missing 

### ISSUE THREAD

**Issue by y-71** [rutzeng/Mini-Pascal-Compiler#1]
when i do the make run command it outs 
java -jar ../compiled_executable/jasmin.jar foo.j
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
foo.j: file not found
make: *** [Makefile:29: run] Error 255

**Comment by rctzeng** [comment]
Sorry for not writing instruction very clearly. 
There is one step `$ make gen` that should be executed before `$make run`.
I've updated the `README.md` file. Let me know if the problem still exists.
